services:
  - type: web
    name: mytube
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
